// app/actions/import.ts — batch import tickets with dedupe-by-phone.

"use server";

import { pbAdmin } from "@/lib/pb/server";
import { paths } from "@/lib/paths";
import { getAppUser } from "@/lib/pb/server-auth";
import { logAction } from "@/lib/pb/log";
import { parseImportedDate, type ParsedTicket } from "@/lib/import-export";
import { revalidatePath } from "next/cache";
import { fillShareUrls } from "@/app/actions/tickets";

export async function importTickets(
  records: ParsedTicket[],
  existingKeys: string[]
): Promise<
  | { ok: true; imported: number; duplicates: number }
  | { ok: false; error: string }
> {
  const user = await getAppUser();
  if (!user) return { ok: false, error: "Not authenticated." };

  const pb = await pbAdmin();
  // Dedup by composite key: phone + name (so parent + kids with same phone but
  // different names are NOT treated as duplicates).
  const existingSet = new Set(existingKeys);
  let imported = 0;
  let duplicates = 0;

  for (const record of records) {
    const dedupKey = record.phone + ":" + record.name.toLowerCase();
    if (existingSet.has(dedupKey)) {
      duplicates++;
      continue;
    }
    existingSet.add(dedupKey);

    const scannedState = record.status === "arrived";
    const scannedAtTime = scannedState
      ? (parseImportedDate(record.entryTimeRaw) ?? Date.now())
      : null;

    const ticketData = {
      name: record.name,
      gender: record.gender,
      age: Number(record.age) || 18,
      phone: "+91" + record.phone,
      ticketType: record.ticketType,
      status: record.status,
      scanned: scannedState,
      scannedAt: scannedAtTime,
      scannedBy: scannedState ? "Import" : "",
      createdBy: user.username,
      createdAt: Date.now(),
      gate: "",
      scannedAtGate: "",
      groupId: record.groupId ?? "",
      parentName: record.parentName ?? "",
    };

    let created;
    if (record.id) {
      // Preserve the original id on re-import when it's a valid PB id
      // (^[a-z0-9]{15}$); legacy Firestore ids aren't — fall back to an
      // autogenerated id rather than failing the whole import.
      try {
        created = await pb.collection(paths.ticketsCollection).create({ ...ticketData, id: String(record.id).trim() });
      } catch {
        created = await pb.collection(paths.ticketsCollection).create(ticketData);
      }
    } else {
      created = await pb.collection(paths.ticketsCollection).create(ticketData);
    }
    await fillShareUrls(pb, created.id);
    imported++;
  }

  await logAction(
    user,
    "IMPORT_DATA",
    `Imported ${imported} guests (${duplicates} duplicates skipped).`
  );
  revalidatePath("/guests");
  return { ok: true, imported, duplicates };
}
