// app/actions/roles.ts — CRUD for the dynamic roles collection.
// Admin creates roles, adds staff (name+email), and the app reads them live.

"use server";

import { pbAdmin } from "@/lib/pb/server";
import { paths } from "@/lib/paths";
import { getAppUser } from "@/lib/pb/server-auth";
import { logAction } from "@/lib/pb/log";
import type { StaffMember, StaffRole } from "@/lib/types";

/** Fetch all roles (admin only). */
export async function fetchRoles(): Promise<
  { ok: true; roles: StaffRole[] } | { ok: false; error: string }
> {
  const user = await getAppUser();
  if (!user) return { ok: false, error: "Not authenticated." };
  if (user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const pb = await pbAdmin();
  const records = await pb.collection(paths.rolesCollection).getFullList();
  const roles: StaffRole[] = records.map((r) => ({
    id: r.id,
    name: String(r.name ?? r.id),
    staff: (r.staff as StaffMember[]) ?? [],
    createdAt: Number(r.createdAt ?? 0),
  }));
  return { ok: true, roles };
}

/** Create a new role. */
export async function createRole(
  roleName: string
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const name = roleName.trim();
  if (!name) return { ok: false, error: "Role name is required." };

  const pb = await pbAdmin();
  // Duplicate check by NAME (not id — PB ids are autogenerated 15-char
  // strings; the original app used the name as the Firestore doc id, which
  // PB's id validation rejects).
  const existing = await pb.collection(paths.rolesCollection).getFullList({ fields: "name" });
  if (existing.some((r) => String(r.name ?? "").toLowerCase() === name.toLowerCase())) {
    return { ok: false, error: "Role already exists." };
  }

  await pb.collection(paths.rolesCollection).create({ name, staff: [], createdAt: Date.now() });
  await logAction(user, "LOCK_ACTION", `Created role "${name}".`);
  return { ok: true };
}

/** Add a staff member (name + email) to a role. */
export async function addStaffToRole(
  roleId: string,
  staffName: string,
  staffEmail: string,
  gateId?: string | null
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const name = staffName.trim();
  const email = staffEmail.trim().toLowerCase();
  if (!name || !email)
    return { ok: false, error: "Name and email are required." };

  const pb = await pbAdmin();
  let rec;
  try {
    rec = await pb.collection(paths.rolesCollection).getOne(roleId);
  } catch {
    return { ok: false, error: "Role not found." };
  }

  const staff: StaffMember[] = (rec.staff as StaffMember[]) ?? [];
  if (staff.some((s) => s.email.toLowerCase() === email))
    return { ok: false, error: "Staff member already exists in this role." };

  staff.push({ name, email, ...(gateId ? { gateId } : {}) });
  await pb.collection(paths.rolesCollection).update(roleId, { staff });
  await logAction(
    user,
    "LOCK_ACTION",
    `Added staff "${name}" (${email}) to role "${roleId}".`
  );
  return { ok: true };
}

/** Bulk add multiple staff members to a role. Skips duplicates by email.
 *  Returns the count added and skipped. */
export async function bulkAddStaffToRole(
  roleId: string,
  members: { name: string; email: string }[]
): Promise<{ ok: true; added: number; skipped: number } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const pb = await pbAdmin();
  let rec;
  try {
    rec = await pb.collection(paths.rolesCollection).getOne(roleId);
  } catch {
    return { ok: false, error: "Role not found." };
  }

  const staff: StaffMember[] = (rec.staff as StaffMember[]) ?? [];
  const existingEmails = new Set(staff.map((s) => s.email.toLowerCase()));

  let added = 0;
  let skipped = 0;
  for (const m of members) {
    const name = m.name.trim();
    const email = m.email.trim().toLowerCase();
    if (!name || !email) { skipped++; continue; }
    if (existingEmails.has(email)) { skipped++; continue; }
    staff.push({ name, email });
    existingEmails.add(email);
    added++;
  }

  if (added > 0) await pb.collection(paths.rolesCollection).update(roleId, { staff });
  if (added > 0) {
    await logAction(
      user,
      "LOCK_ACTION",
      `Bulk added ${added} staff to role "${roleId}" (${skipped} skipped).`
    );
  }
  return { ok: true, added, skipped };
}

/** Update a staff member's name and/or email within a role. */
export async function updateStaffInRole(
  roleId: string,
  oldEmail: string,
  newName: string,
  newEmail: string,
  gateId?: string | null
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const name = newName.trim();
  const email = newEmail.trim().toLowerCase();
  if (!name || !email)
    return { ok: false, error: "Name and email are required." };

  const pb = await pbAdmin();
  let rec;
  try {
    rec = await pb.collection(paths.rolesCollection).getOne(roleId);
  } catch {
    return { ok: false, error: "Role not found." };
  }

  const staff: StaffMember[] = (rec.staff as StaffMember[]) ?? [];
  const idx = staff.findIndex(
    (s) => s.email.toLowerCase() === oldEmail.toLowerCase()
  );
  if (idx === -1) return { ok: false, error: "Staff member not found." };

  staff[idx] = { ...staff[idx], name, email, ...(gateId !== undefined ? { gateId } : {}) };
  await pb.collection(paths.rolesCollection).update(roleId, { staff });
  await logAction(
    user,
    "LOCK_ACTION",
    `Updated staff in role "${roleId}": ${oldEmail} → ${name} (${email}).`
  );
  return { ok: true };
}

/** Remove a staff member from a role by email.
 *  With Pocketbase, access auto-revokes: getAppUser() rejects any email not in
 *  the roles collection, so the removed staff is logged out on their next
 *  request. No explicit token revoke needed. */
export async function removeStaffFromRole(
  roleId: string,
  staffEmail: string
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const pb = await pbAdmin();
  let rec;
  try {
    rec = await pb.collection(paths.rolesCollection).getOne(roleId);
  } catch {
    return { ok: false, error: "Role not found." };
  }

  const staff: StaffMember[] = (rec.staff as StaffMember[]) ?? [];
  const filtered = staff.filter(
    (s) => s.email.toLowerCase() !== staffEmail.toLowerCase()
  );
  await pb.collection(paths.rolesCollection).update(roleId, { staff: filtered });

  // Check if this email exists in ANY other role.
  const allRoles = await pb.collection(paths.rolesCollection).getFullList({ fields: "staff" });
  const stillExists = allRoles.some((r) => {
    const s = (r.staff as StaffMember[]) ?? [];
    return s.some((m) => m.email.toLowerCase() === staffEmail.toLowerCase());
  });

  await logAction(
    user,
    "LOCK_ACTION",
    `Removed staff (${staffEmail}) from role "${roleId}"${!stillExists ? " and revoked access" : ""}.`
  );
  return { ok: true };
}

/** Delete an entire role. */
export async function deleteRole(
  roleId: string
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await getAppUser();
  if (!user || user.role !== "admin")
    return { ok: false, error: "Admin role required." };

  const pb = await pbAdmin();
  await pb.collection(paths.rolesCollection).delete(roleId);
  await logAction(user, "LOCK_ACTION", `Deleted role "${roleId}".`);
  return { ok: true };
}
